title: "LEIE"
description: "Material docente (2 sesiones) — Máster de investigación"
remote_theme: just-the-docs/just-the-docs

# Ajusta esto al nombre del repositorio (p.ej., /LEIE-GitHub-Pages)
baseurl: "/LineasEmergentes-UJA"

# Idioma/interfaz
search_enabled: true

# Apariencia (toque distinto frente a sitios anteriores)
color_scheme: dark

# Enlaces en la cabecera
aux_links:
  "Repositorio en GitHub":
    - "https://github.com/Samigabacho/LineasEmergentes-UJA"
aux_links_new_tab: true

# Evita warnings por plugins en Pages
plugins:
  - jekyll-seo-tag
